const questions = {
  questions: [
    {
      question_no: 1,
      question_english: "Do you have history of Jaundice?",
      question_hindi: "क्या आपको कभी पीलिया हुआ है?",
      true_next_question: 2,
      false_next_question: 2,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/cld1.png",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 2,
      question_english: "Has jaundice recurred ?",
      question_hindi: "क्या पीलिया की पुनरावृत्ति हुई है?",
      true_next_question: 3,
      false_next_question: 3,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 3,
      question_english:
        "Do you have any history of Altered Sensorium/Delirium?",
      question_hindi:
        "क्या कभी आप गफलत की स्थिति में चले गए थे? यदि हाँ",
      true_next_question: 4,
      false_next_question: 5,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 4,
      question_english:
        "How soon did you experience it after the onset of jaundice ?",
      question_hindi:
        "पीलिया शुरू होने के कितने दिनों बाद आप गफलत में गए थे?",
      true_next_question: 5,
      false_next_question: 5,
      question_answer: "",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "<=7 days/7 दिन से कम",
        option_2: ">7 days/7 दिन से अधिक",
      },
      multiple_choice: [],
    },
    {
      question_no: 5,
      question_english: "Have you undergone any surgery in the past ?",
      question_hindi: "क्या पहले कभी आपका कोई आपरेशन हुआ है?",
      true_next_question: 6,
      false_next_question: 6,
      question_answer: "",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 6,
      question_english: "Have you undergone any liver biopsy in the past ?",
      question_hindi: "क्या पहले कभी आपके लिवर/यकृत का टुकड़ा निकाला गया है ?",
      true_next_question: 7,
      false_next_question: 7,
      question_answer: "",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/cld6.png",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 7,
      question_english:
        "Have you been hospitalised in the past for any liver related sickness?",
      question_hindi:
        "क्या आप पहले कभी किसी लिवर से संबंधित समस्या के लिए अस्पताल में भर्ती हुए हैं ?",
      true_next_question: 8,
      false_next_question: 8,
      question_answer: "",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 8,
      question_english: "Do you consume alcohol ?",
      question_hindi: "क्या आप शराब का सेवन करते हैं ?",
      true_next_question: 9,
      false_next_question: 9,
      question_answer: "",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 9,
      question_english: "Do you have intolerance to fatty foods ?",
      question_hindi:
        "क्या आपका तला हुआ भोजन खाने से कष्ट होता है ?",
      true_next_question: 10,
      false_next_question: 10,
      question_answer: "",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 10,
      question_english: "Do you have history of seizure?",
      question_hindi: "क्या आपको कभी मिरगी का दौरा पड़ा है?",
      true_next_question: 11,
      false_next_question: 11,
      question_answer: "",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 11,
      question_english: "Is there history of change in vision?",
      question_hindi: "क्या दृष्टि/नजर में कोई कमजोरी आई है?",
      true_next_question: 12,
      false_next_question: 12,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 12,
      question_english: "Do you feel sleepy during day time?",
      question_hindi: "क्या आपको दिन में बैठे बैठे नींद आती है?",
      true_next_question: 13,
      false_next_question: 13,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 13,
      question_english: "Do you feel irritable?",
      question_hindi: "क्या आपके मिजाज में चिढ़चिढ़ापन आ रहा है?",
      true_next_question: 14,
      false_next_question: 14,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 14,
      question_english:
        "Does your spouse/friends/relatives complain that you have irrelevant talks?",
      question_hindi:
        "क्या आपके मित्र/रिश्तेदार की यह शिकायत है कि आप बहकी बहकी बातें करते हैं?",
      true_next_question: 15,
      false_next_question: 15,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 15,
      question_english: "Do you forget things easily?",
      question_hindi: "क्या आप चीजें बहुत जल्दी भूलते हैं/आपकी याददाश्त कमजोर हो रही है?",
      true_next_question: 16,
      false_next_question: 16,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 16,
      question_english: "Did you notice tremors in hand?",
      question_hindi: "क्या आपके हाथों में कम्पन होता है?",
      true_next_question: 17,
      false_next_question: 17,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 17,
      question_english: "Have you received any blood transfusion in past?",
      question_hindi: "क्या आपको कभी खून चढ़वाने की आवश्यकता हुई है?",
      true_next_question: 18,
      false_next_question: 18,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 18,
      question_english:
        "Was there any history of infection of umbilical cord at your birth?",
      question_hindi:
        "क्या पैदाइश के बाद आपकी नाभि में कोई संक्रमण हुआ था?",
      true_next_question: 19,
      false_next_question: 19,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 19,
      question_english:
        "Do you get easily fatigued/feeling of weakness/tiredness?",
      question_hindi:
        "क्या आप बहुत जल्दी थक जाते हैं या कमजोरी महसूस करते हैं?",
      true_next_question: 20,
      false_next_question: 20,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 20,
      question_english: "Do you have difficulty while walking?",
      question_hindi: "क्या आप से चलने में काेई कष्ट हाेता है?",
      true_next_question: 21,
      false_next_question: 21,
      question_answer: "",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 21,
      question_english: "Have you lost weight in the recent past?",
      question_hindi: "क्या निकट भूतकाल में वजन कम हुआ है?",
      true_next_question: 22,
      false_next_question: 22,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 22,
      question_english: "Do you have feeling of loss of health?",
      question_hindi: "क्या आपकी सेहत में कुछ गिरावट आ रही है?",
      true_next_question: 23,
      false_next_question: 23,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 23,
      question_english: "Do you have loss of appetite?",
      question_hindi: "क्या आपको भूख कम हो गई र्है?",
      true_next_question: 24,
      false_next_question: 24,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 24,
      question_english:
        "Have you noticed any change in complexion/blackening of skin?",
      question_hindi: "क्या आपकी त्वचा के रंग में कालापन आ रहा है?",
      true_next_question: 25,
      false_next_question: 25,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 25,
      question_english: "Did you observe dilated veins in abdomen?",
      question_hindi: "क्या आपके पेट में कुछ फूली हुई /नीली नसें दिखने लग गई है?",
      true_next_question: 26,
      false_next_question: 26,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/cld25.png",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 26,
      question_english:
        "Do you have pain/discomfort in right upper abdomen or tenderness?",
      question_hindi:
        "क्या आपके पेट के ऊपर के दाहिने हिस्से में कोई कष्ट / दर्द / दबाने पर दर्द महसूस होता है?",
      true_next_question: 27,
      false_next_question: 27,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 27,
      question_english: "Have you undergone abdomen fluid tapping?",
      question_hindi: "क्या आपके पेट में से कभी पानी निकाला गया है ?",
      true_next_question: 28,
      false_next_question: 28,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 28,
      question_english: "Did you observe any swelling in abdomen?",
      question_hindi: "क्या आपके पेट में कोई सूजन महसूस की है?",
      true_next_question: 29,
      false_next_question: 29,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 29,
      question_english: "Did you observe any swelling in lower limb?",
      question_hindi: "क्या आपके पैरों में कोई सूजन तो नहीं आई?",
      true_next_question: 30,
      false_next_question: 30,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/cld29.png",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 30,
      question_english: "Have you passed blood in stools?",
      question_hindi: "क्या आपके मल में कभी खून आता है?",
      true_next_question: 31,
      false_next_question: 31,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 31,
      question_english: "Have you passed loose stools?",
      question_hindi: "क्या आपको कभी दस्त/पतला मल आता है?",
      true_next_question: 32,
      false_next_question: 32,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 32,
      question_english: "Have people told you that you walk during sleep?",
      question_hindi: "क्या आपको नींद में चलने की आदत तो नहीं है ?",
      true_next_question: 33,
      false_next_question: 33,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 33,
      question_english:
        "Have you been losing your body hair? (private parts: axilla/groin/limbs/eyebrows)?",
      question_hindi:
        "क्या आपके शरीर से बाल झड़ रहे है ;गुप्तांगः बगल /जंघा/ भ ुजाऐं /टांगें / भौहें ?",
      true_next_question: 34,
      false_next_question: 34,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 34,
      question_english: "Does your mouth have foul smell?",
      question_hindi: "क्या आपके मुंह से दुर्गंध आती है ?",
      true_next_question: 35,
      false_next_question: 35,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 35,
      question_english: "Is your libido decreased than before?",
      question_hindi: "क्या आपकी कामेच्छा पहले से कम हो गई है?",
      true_next_question: 36,
      false_next_question: 36,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 36,
      question_english:
        "Did you/your spouse notice any change in size of testicles?",
      question_hindi:
        "क्या आपने या आपके जीवनसाथी ने अंडकोष के आकार में कोई बिगाड़ देखा है?",
      true_next_question: 37,
      false_next_question: 37,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 37,
      question_english: "Do you have any history of fever?",
      question_hindi: "क्या आपको बुखार/ज्वर आता रहा है?",
      true_next_question: 38,
      false_next_question: 38,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 38,
      question_english: "Any history of recurrent boils?",
      question_hindi: "क्या आपको फोड़े तो नहीं निकलते हैं?",
      true_next_question: 39,
      false_next_question: 39,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 39,
      question_english: "Do you have any history of diabetes?",
      question_hindi: "क्या आपको डायबिटीज/मधुमेह की शिकायत थी/है? ",
      true_next_question: 40,
      false_next_question: 41,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 40,
      question_english:
        "Have you experienced worsening of diabetes (5-6 years) or change in the dosage of insulin or other antidiabetic drugs in recent times?",
      question_hindi:
        "क्या आपकी डायबिटीज पिछले कुछ समय में बिगड़ी है या आपकी डायबिटीज की दवाएं बढ़ी हैं?",
      true_next_question: 41,
      false_next_question: 41,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 41,
      question_english: "Do you get bruises easily due to minor injuries?",
      question_hindi: "क्या हल्की सी चीट से आपको घाव/नील पड़ जाते हैं?",
      true_next_question: 42,
      false_next_question: 42,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 42,
      question_english:
        "Have you noticed any enlargement of your breast (gynecomastia)?",
      question_hindi:
        "क्या आपके स्तन तो नहीं बढ़ गए ह ैं?",
      true_next_question: 43,
      false_next_question: 43,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 43,
      question_english:
        "Do you have spontaneous bleeding:\na. gum / गोंद\nb. nose / नाक \nc. red spot / लाल जगह",
      question_hindi: "क्या आपके मसूड़े से या नाक/नकसीर से खून तो नहीं बहता है",
      true_next_question: 44,
      false_next_question: 44,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 44,
      question_english: "Do you have blood in sputum?",
      question_hindi: "क्या आपके बलगम में कभी खून आया है?",
      true_next_question: 45,
      false_next_question: 45,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 45,
      question_english: "Do you take any herbal medications?",
      question_hindi: "क्या आप किसी जड़ी-बूटी का सेवन करते हैं?",
      true_next_question: 46,
      false_next_question: 46,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 46,
      question_english: "Have you ever been diagnosed with tuberculosis?",
      question_hindi: "क्या आपको कभी तपेदिक/टीबी का पता चला है? ",
      true_next_question: 47,
      false_next_question: 48,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 47,
      question_english: "Have you received any drugs for tuberculosis?",
      question_hindi: "क्या आपका कभी तपेदिक/टीबी का इलाज हुआ है?",
      true_next_question: 48,
      false_next_question: 48,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 48,
      question_english: "Do you have any shortness of breath?",
      question_hindi: "क्या आपकी सांस फूलती हैं?",
      true_next_question: 49,
      false_next_question: 49,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 49,
      question_english: "Have you undergone any endoscopic intervention?",
      question_hindi: "क्या आपका इंडोस्कोपी से कोई उपचार किया गया है?",
      true_next_question: 50,
      false_next_question: 50,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/cld49.png",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 50,
      question_english: "Do you take paracetamol frequently?",
      question_hindi: "क्या आप पैरासिटामोल का अक्सर सेवन करते हैं?",
      true_next_question: 51,
      false_next_question: 51,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 51,
      question_english: "Do you have retrosternal chest pain?",
      question_hindi: "क्या आपके बीच छाती में कभी जलन/दर्द होती है?",
      true_next_question: 52,
      false_next_question: 52,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 52,
      question_english: "Do you have vomiting?",
      question_hindi: "क्या आपको उल्टी होती है?",
      true_next_question: 53,
      false_next_question: 54,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 53,
      question_english: "Do you have blood vomiting?",
      question_hindi: "क्या आपको उल्टी में कभी खून आया है?",
      true_next_question: 54,
      false_next_question: 54,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 54,
      question_english:
        "Do you have black/tarry stools foul smelling stools sticking to the pan?",
      question_hindi:
        "क्या आपको कोलतार जैसा या बदबूदार चिपकने वाला मल तो नहीं आता हैं?",
      true_next_question: 55,
      false_next_question: 55,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 55,
      question_english: "Has your urine output decreased?",
      question_hindi: "क्या आपकी पेशाब की मात्रा कम हो गई है?",
      true_next_question: 56,
      false_next_question: 56,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 56,
      question_english: "Do you get recurrent bouts of cough?",
      question_hindi: "क्या आपको खांसी के दौरे तो नहीं आते हैं?",
      true_next_question: 0,
      false_next_question: 0,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
  ],
};

export default questions;
