const questions = {
  questions: [
    {
      question_no: 1,
      question_english: "Have you noticed the yellowing of skin/eyes?",
      question_hindi: "क्या आपको पीलिया है /क्या आपका शरीर और आंखे पीली है?",
      true_next_question: 2,
      false_next_question: 9,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/hpb1.png",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 2,
      question_english: "Is it progressively increasing?",
      question_hindi: "क्या यह लगातार बढ़ रहा है?",
      true_next_question: 3,
      false_next_question: 3,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 3,
      question_english:
        "Is it associated with itching - during the day or night or both?",
      question_hindi:
        "क्या पीलियाँ के साथ खुजली होती है? (दिन में / रात मे / दोनो)",
      true_next_question: 4,
      false_next_question: 4,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 4,
      question_english: "Does itching disturb your sleep?",
      question_hindi: "क्या खुजली आपको सोने नही देती?",
      true_next_question: 5,
      false_next_question: 5,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 5,
      question_english:
        "Have you undergone any procedure for correction of jaundice?",
      question_hindi: "क्या पीलिया खत्म करने के लिए कोई क्रिया/प्रयोग किया है?",
      true_next_question: 6,
      false_next_question: 9,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 6,
      question_english: "Was the procedure done with an endoscope?",
      question_hindi: "क्या क्रिया/प्रयोग एंडोस्कोप से की गई थी?",
      true_next_question: 7,
      false_next_question: 7,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/hpb6.png",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 7,
      question_english:
        "Was the procedure ultrasound-guided in X-ray department?",
      question_hindi:
        "क्या प्रोसीजर एक्स-रे डिपार्टमेंट में अल्ट्रासाउंड की मदद से किया गया था?",
      true_next_question: 8,
      false_next_question: 8,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 8,
      question_english: "Did it involve the placement of a tube in your liver?",
      question_hindi: "क्या इसमें लिवर में ट्यूब डाली गई थी?",
      true_next_question: 9,
      false_next_question: 9,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/hpb8.jpg",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 9,
      question_english: "Did you ever have jaundice in the past?",
      question_hindi: "क्या आपको पहले कभी पीलिया हुआ है?",
      true_next_question: 10,
      false_next_question: 10,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 10,
      question_english: "Any change in stool colour?",
      question_hindi: "क्या आपके दस्त का रंग बदला है?",
      true_next_question: 11,
      false_next_question: 13,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 11,
      question_english: "Is the stool lighter in colour?",
      question_hindi: "क्याआपके दस्त का रंग हल्का या सफेद हुआ है?",
      true_next_question: 13,
      false_next_question: 12,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/hpb11.jpg",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 12,
      question_english: "Is the stool black in colour?",
      question_hindi: "क्या आपके दस्त का रंग काला हुआ है?",
      true_next_question: 13,
      false_next_question: 13,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/hpb12.png",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 13,
      question_english: "Is the urine dark in colour?",
      question_hindi: "क्या आप आपके पेशाब का रंग गहरा हुआ है?",
      true_next_question: 14,
      false_next_question: 15,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 14,
      question_english: "Does urine look like mustard oil?",
      question_hindi: "क्या आपकी पेशाब सरसो के तेल के जैसी पीली होती है?",
      true_next_question: 15,
      false_next_question: 15,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/hpb14.jpg",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 15,
      question_english: "Do you pass loose stools?",
      question_hindi: "क्या आपको पतली दस्त होती है?",
      true_next_question: 16,
      false_next_question: 16,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 16,
      question_english: "Do you feel feverish?",
      question_hindi: "क्या आपको बुखार जैसा लगता है?",
      true_next_question: 17,
      false_next_question: 17,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 17,
      question_english: "Do you get fever?",
      question_hindi: "क्या आपको बुखार आता है?",
      true_next_question: 18,
      false_next_question: 21,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 18,
      question_english: "Is there profuse sweating with fever or after fever?",
      question_hindi: "क्या आपको बुखार के साथ या उसके बाद बहुत पसीना आता है?",
      true_next_question: 19,
      false_next_question: 19,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 19,
      question_english: "Are there multiple episodes of fever?",
      question_hindi: "क्या आपको बार बार बुखार आता है?",
      true_next_question: 20,
      false_next_question: 20,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 20,
      question_english:
        "Is fever associated with feeling of extreme cold? Does your body shake during fever?",
      question_hindi:
        "क्या बुखार के कारण बहुत जयादा ठंड/ कपकपी/ जूड़ी लगती है?",
      true_next_question: 21,
      false_next_question: 21,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 21,
      question_english: "Do you have pain in the abdomen?",
      question_hindi: "क्या आपके पेट में दर्द है?",
      true_next_question: 22,
      false_next_question: 40,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 22,
      question_english: "Where do you have pain in your abdomen?",
      question_hindi: "आपके पेट के किस हिस्से में दर्द हो रहा है?",
      true_next_question: 27,
      false_next_question: 27,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [
        {
          question_no: 23,
          question_english: "Does it pain in mid abdomen?",
          question_hindi: "क्या आपके पेट में ऊपर के हिस्से में दर्द है?",
          true_next_question: 27,
          false_next_question: 27,
          question_answer: "ABSENT",
          question_desc: "",
          question_img: "",
          option: {
            option_1: "YES/हाँ",
            option_2: "NO/नहीं",
          },
          multiple_choice: [],
        },
        {
          question_no: 24,
          question_english: "Does it pain upper right abdomen?",
          question_hindi: "क्या आपके पेट में ऊपर के दाएं हिस्से में दर्द है?",
          true_next_question: 27,
          false_next_question: 27,
          question_answer: "ABSENT",
          question_desc: "",
          question_img: "",
          option: {
            option_1: "YES/हाँ",
            option_2: "NO/नहीं",
          },
          multiple_choice: [],
        },
        {
          question_no: 25,
          question_english: "Does it pain in upper left abdomen?",
          question_hindi: "क्या आपके पेट में ऊपर के बाएं हिस्से में दर्द है?",
          true_next_question: 27,
          false_next_question: 27,
          question_answer: "ABSENT",
          question_desc: "",
          question_img: "",
          option: {
            option_1: "YES/हाँ",
            option_2: "NO/नहीं",
          },
          multiple_choice: [],
        },
        {
          question_no: 26,
          question_english: "Does it pain in the upper mid abdomen?",
          question_hindi: "क्या आपके पेट में ऊपर के हिस्से में सूजन है?",
          true_next_question: 27,
          false_next_question: 27,
          question_answer: "ABSENT",
          question_desc: "",
          question_img: "",
          option: {
            option_1: "YES/हाँ",
            option_2: "NO/नहीं",
          },
          multiple_choice: [],
        },
      ],
    },
    {
      question_no: 23,
      question_english: "Does it pain in mid abdomen?",
      question_hindi: "क्या आपके पेट में ऊपर के हिस्से में दर्द है?",
      true_next_question: 27,
      false_next_question: 27,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 24,
      question_english: "Does it pain upper right abdomen?",
      question_hindi: "क्या आपके पेट में ऊपर के दाएं हिस्से में दर्द है?",
      true_next_question: 27,
      false_next_question: 27,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 25,
      question_english: "Does it pain in upper left abdomen?",
      question_hindi: "क्या आपके पेट में ऊपर के बाएं हिस्से में दर्द है?",
      true_next_question: 27,
      false_next_question: 27,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 26,
      question_english: "Does it pain in the upper mid abdomen?",
      question_hindi: "क्या आपके पेट में ऊपर के हिस्से में सूजन है?",
      true_next_question: 27,
      false_next_question: 27,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 27,
      question_english: "Is your pain crampy?",
      question_hindi: "क्या आपके पेट में मरोड़ वाला दर्द होता है?",
      true_next_question: 28,
      false_next_question: 28,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 28,
      question_english: "Is your pain sharp pricking in nature?",
      question_hindi: "क्या आपका पेट का दर्द तेज चुभन जैसा होता है?",
      true_next_question: 29,
      false_next_question: 29,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 29,
      question_english: "Is your pain vague/dull type of pain?",
      question_hindi: "क्या आपका पेट का दर्द मामूली/हल्का होता है?",
      true_next_question: 30,
      false_next_question: 30,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 30,
      question_english: "Is your pain continuous throughout the day?",
      question_hindi: "क्या आपके पेट में दर्द हर वक्त दिन भर होता है?",
      true_next_question: 31,
      false_next_question: 31,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 31,
      question_english: "Does it pain in the back?",
      question_hindi: "क्या आपको पीठ में दर्द होता है?",
      true_next_question: 32,
      false_next_question: 32,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 32,
      question_english: "Does your pain radiate to the back?",
      question_hindi: "क्या आपका पेट का दर्द पीठ में जाता है?",
      true_next_question: 33,
      false_next_question: 33,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 33,
      question_english: "Does your pain radiate to the shoulder?",
      question_hindi: "क्या आपका पेट का दर्द कंधे तक जाता है?",
      true_next_question: 34,
      false_next_question: 34,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 34,
      question_english: "Does your pain come and go on and off?",
      question_hindi: "क्या पेट का दर्द आता जाता रहता है?",
      true_next_question: 35,
      false_next_question: 35,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 35,
      question_english: "Does your pain resolve spontaneously?",
      question_hindi: "क्या पेट का दर्द अपने आप ठीक हो जाता है?",
      true_next_question: 36,
      false_next_question: 36,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 36,
      question_english: "Do you use hot fomentation for pain relief?",
      question_hindi: "क्या आप दर्द से राहत के लिए गर्म सिकाई करते हैं?",
      true_next_question: 37,
      false_next_question: 37,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/hpb35.jpg",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 37,
      question_english: "Does it need oral or IV pain killers?",
      question_hindi:
        "क्या पेट के दर्द के लिए दवा या IV इन्जेक्शन लेना पड़ता है?",
      true_next_question: 38,
      false_next_question: 38,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 38,
      question_english:
        "Did it ever require admission to a hospital or nursing home?",
      question_hindi:
        "क्या पेट के दर्द की वजह से अस्पताल या नर्सिंग होम में भर्ती होना पड़ा है?",
      true_next_question: 39,
      false_next_question: 39,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 39,
      question_english:
        "Is there any recent change in the character or pattern of pain?",
      question_hindi:
        "क्या हाल में पेट के दर्द के रूप में कोई बदलाव महसूस हुआ है?",
      true_next_question: 40,
      false_next_question: 40,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 40,
      question_english: "Do you have nausea?",
      question_hindi: "क्या आपको जी मिचलाता है?",
      true_next_question: 41,
      false_next_question: 42,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 41,
      question_english: "Is nausea occasional?",
      question_hindi: "क्या आपका कभी-कभी जी मिचलाता है?",
      true_next_question: 42,
      false_next_question: 42,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 42,
      question_english: "Do you have vomiting?",
      question_hindi: "क्या आपको उल्टी होती है?",
      true_next_question: 43,
      false_next_question: 57,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 43,
      question_english: "What is the color of your vomit?",
      question_hindi: "उल्टी का रंग कैसा है?",
      true_next_question: 50,
      false_next_question: 50,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [
        {
          question_no: 44,
          question_english: "Is it yellow in color?",
          question_hindi: "क्या उल्टी का रंग पीला होता है?",
          true_next_question: 50,
          false_next_question: 50,
          question_answer: "ABSENT",
          question_desc: "",
          question_img: "",
          option: {
            option_1: "YES/हाँ",
            option_2: "NO/नहीं",
          },
          multiple_choice: [],
        },
        {
          question_no: 45,
          question_english: "Is it green in color?",
          question_hindi: "क्या उल्टी का रंग हरा होता है?",
          true_next_question: 50,
          false_next_question: 50,
          question_answer: "ABSENT",
          question_desc: "",
          question_img: "",
          option: {
            option_1: "YES/हाँ",
            option_2: "NO/नहीं",
          },
          multiple_choice: [],
        },
        {
          question_no: 46,
          question_english: "Is it white in color?",
          question_hindi: "क्या उल्टी का रंग सफेद होता है?",
          true_next_question: 50,
          false_next_question: 50,
          question_answer: "ABSENT",
          question_desc: "",
          question_img: "",
          option: {
            option_1: "YES/हाँ",
            option_2: "NO/नहीं",
          },
          multiple_choice: [],
        },
        {
          question_no: 47,
          question_english: "Is it red in color?",
          question_hindi: "क्या उल्टी का रंग लाल होता है?",
          true_next_question: 50,
          false_next_question: 50,
          question_answer: "ABSENT",
          question_desc: "",
          question_img: "",
          option: {
            option_1: "YES/हाँ",
            option_2: "NO/नहीं",
          },
          multiple_choice: [],
        },
        {
          question_no: 48,
          question_english: "Is it dark brown?",
          question_hindi: "क्या उल्टी का रंग गहरा लाल / काला होता है?",
          true_next_question: 50,
          false_next_question: 50,
          question_answer: "ABSENT",
          question_desc: "",
          question_img: "",
          option: {
            option_1: "YES/हाँ",
            option_2: "NO/नहीं",
          },
          multiple_choice: [],
        },
        {
          question_no: 49,
          question_english: "Is it black in color?",
          question_hindi: "क्या उल्टी का रंग काला (कोलतार जैसा) होता है?",
          true_next_question: 50,
          false_next_question: 50,
          question_answer: "ABSENT",
          question_desc: "",
          question_img: "",
          option: {
            option_1: "YES/हाँ",
            option_2: "NO/नहीं",
          },
          multiple_choice: [],
        },
      ],
    },
    {
      question_no: 44,
      question_english: "Is it yellow in color?",
      question_hindi: "क्या उल्टी का रंग पीला होता है?",
      true_next_question: 50,
      false_next_question: 50,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 45,
      question_english: "Is it green in color?",
      question_hindi: "क्या उल्टी का रंग हरा होता है?",
      true_next_question: 50,
      false_next_question: 50,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 46,
      question_english: "Is it white in color?",
      question_hindi: "क्या उल्टी का रंग सफेद होता है?",
      true_next_question: 50,
      false_next_question: 50,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 47,
      question_english: "Is it red in color?",
      question_hindi: "क्या उल्टी का रंग लाल होता है?",
      true_next_question: 50,
      false_next_question: 50,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 48,
      question_english: "Is it dark brown?",
      question_hindi: "क्या उल्टी का रंग गहरा लाल / काला होता है?",
      true_next_question: 50,
      false_next_question: 50,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 49,
      question_english: "Is it black in color?",
      question_hindi: "क्या उल्टी का रंग काला (कोलतार जैसा) होता है?",
      true_next_question: 50,
      false_next_question: 50,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 50,
      question_english: "Is your vomiting mouthful?",
      question_hindi: "क्या आपको पूरा मुँह भरकर उल्टी आती है?",
      true_next_question: 51,
      false_next_question: 51,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 51,
      question_english: "Does it come out with force?",
      question_hindi: "क्या आपको उल्टी तेजी से बाहर आती है?",
      true_next_question: 52,
      false_next_question: 52,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 52,
      question_english:
        "Does it contain any food particles from the previous meal?",
      question_hindi: "क्या आपको पिछला खाना उल्टी में बाहर आता है?",
      true_next_question: 53,
      false_next_question: 53,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 53,
      question_english: "Are the food particles digested?",
      question_hindi: "क्या आपकी उल्टी में खाना पचा हुआ होता है?",
      true_next_question: 55,
      false_next_question: 54,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 54,
      question_english: "Are the food particles undigested?",
      question_hindi: "क्या आपकी उल्टी में सारा खाना बाहर निकल आता है?",
      true_next_question: 55,
      false_next_question: 55,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 55,
      question_english: "Does it occur immediately after meals?",
      question_hindi: "क्या यह खाने के तुरंत बाद होता है?",
      true_next_question: 56,
      false_next_question: 56,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 56,
      question_english: "Does it occur after a few hours of food intake?",
      question_hindi: "क्या यह खाना खाने के कुछ घंटे बाद होता है?",
      true_next_question: 57,
      false_next_question: 57,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 57,
      question_english: "Is your breath foul smelling?",
      question_hindi: "क्या आपकी सांस में बदबू आती है?",
      true_next_question: 58,
      false_next_question: 59,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 58,
      question_english: "Does it smell like stale fruits?",
      question_hindi: "तो क्या वो सड़े हुए फल जैसी है?",
      true_next_question: 59,
      false_next_question: 59,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 59,
      question_english: "Have you lost your appetite/stopped feeling hungry?",
      question_hindi: "क्या आपको भूख लगना बंद हो गई है?",
      true_next_question: 60,
      false_next_question: 60,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 60,
      question_english:
        "Do you feel full after having a small quantity of food compared to your normal diet?",
      question_hindi:
        "क्या आप सामान्य आहार की तुलना में कम मात्रा में भोजन करने के बाद भी पेट भरा हुआ महसूस करते हैं?",
      true_next_question: 61,
      false_next_question: 61,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 61,
      question_english:
        "Have you lost weight or noticed loosening of clothes and jewellery? (Measured loss of weight - > 5kg in 1-3 months, > 10kg in 6 months, > 20kg in 12 months)",
      question_hindi:
        "क्या आपका वजन कम हुआ है या आपने कपड़ों और गहनों को ढीला होते देखा है? (वजन में कमी -> 1-3 महीने में 5 किलो, 6 महीने में 10 किलो, 12 महीने में >20 किलो)",
      true_next_question: 62,
      false_next_question: 62,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 62,
      question_english:
        "Do you feel lethargic/ less energetic/ easily fatigued/ generalised weakness?",
      question_hindi: "क्या आप सुस्त / कम ऊर्जावान महसूस करते हैं?",
      true_next_question: 63,
      false_next_question: 63,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 63,
      question_english:
        "Do you feel generalised body ache / muscle or limb pain?",
      question_hindi: "क्या आपको आसानी से थकान या कमजोरी महसूस होती है?",
      true_next_question: 64,
      false_next_question: 64,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 64,
      question_english: "Do you have night sweats?",
      question_hindi: "क्या रात में पसीना आता है?",
      true_next_question: 65,
      false_next_question: 65,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 65,
      question_english: "Have you noticed any swelling in your legs?",
      question_hindi: "क्या दोनों पैरों में सूजन दिखती है?",
      true_next_question: 66,
      false_next_question: 67,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/hpb63.jpg",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 66,
      question_english: "Does the swelling come and go?",
      question_hindi: "क्या सूजन आती और जाती है?",
      true_next_question: 67,
      false_next_question: 67,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 67,
      question_english:
        "Does your footwear and socks leave a mark on the foot/leg?",
      question_hindi:
        "क्या पैरों में चप्पल/जूते / मोजे के निशान लम्बे समय तक रह जाते हैं?",
      true_next_question: 68,
      false_next_question: 68,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 68,
      question_english: "Is your abdomen bigger than before?",
      question_hindi: "क्या आपका पेट पहले से बड़ा/ फूला है?",
      true_next_question: 69,
      false_next_question: 69,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/hpb66.jpg",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 69,
      question_english:
        "Have you noticed any recent change in your waist size or tightening of your pants / belt leaving imprints on your belly?",
      question_hindi:
        "क्या आपके पैंट या कमर के साइज में बदलाव आया है? क्या आपकी कमर पर बेल्ट का निशान लम्बे समय तक रह जाता है?",
      true_next_question: 70,
      false_next_question: 70,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 70,
      question_english:
        "Do you consume alcohol or tobacco in any form? (Cigarettes/ beedi/ pan masala/gutka)?",
      question_hindi:
        "क्या आप शराब / तम्बाकू / बीड़ी / गुटका / धूम्र पान या अन्य नशा करते है?",
      true_next_question: 71,
      false_next_question: 71,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 71,
      question_english:
        "Was any of your family members or blood relation diagnosed with any malignancy?",
      question_hindi:
        "क्या आपके परिवार में किसी को कैंसर की बिमारी हुई है? (माता/पिता के साइड में )",
      true_next_question: 72,
      false_next_question: 72,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 72,
      question_english: "Any history of gall stone disease?",
      question_hindi: "क्या आपको पित्त की थैली में पथरी की बिमारी हुई है?",
      true_next_question: 73,
      false_next_question: 73,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 73,
      question_english:
        "Any Previous surgery of liver/gall bladder/bile duct/pancreas?",
      question_hindi:
        "क्या आपकी लिवर, पित्ताशय, पित्त की नली या पेनक्रियाज की कोई आपरेशन हुआ है?",
      true_next_question: 74,
      false_next_question: 74,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 74,
      question_english:
        "Have you ever been diagnosed with any liver disease/infection?",
      question_hindi: "क्या आपको लिवर संबंधित बिमारी या इन्फेक्शन हुआ है?",
      true_next_question: 75,
      false_next_question: 75,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 75,
      question_english:
        "Have you ever required hospital admission for any disease of the pancreas?",
      question_hindi:
        "क्या आपको कभी अग्न्याशय/ पैनक्रियाज की किसी बीमारी के लिए अस्पताल में भर्ती होने की आवश्यकता पड़ी है?",
      true_next_question: 76,
      false_next_question: 76,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 76,
      question_english: "Do you have diabetes?",
      question_hindi: "क्या आपको डायबिटीज है?",
      true_next_question: 77,
      false_next_question: 79,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 77,
      question_english: "If yes, for how many years have you had diabetes?",
      question_hindi: "यदि हाँ, तो आपको कितने वर्षों से डायबिटीज है?",
      true_next_question: 78,
      false_next_question: 78,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "< 1year YES/हाँ",
        option_2: "> 1year NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 78,
      question_english: "Has your diabetes worsened recently?",
      question_hindi: "क्या हाल ही में आपकी डायबिटीज की हालत बिगड़ गई है?",
      true_next_question: 79,
      false_next_question: 79,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 79,
      question_english: "Is there any history of diabetes in your family?",
      question_hindi: "क्या आपके परिवार में किसी को डायबिटीज है?",
      true_next_question: 80,
      false_next_question: 80,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 80,
      question_english: "Do you notice any swelling in your abdomen?",
      question_hindi: "क्या आपको अपने पेट में कोई सूजन महसूस होती है?",
      true_next_question: 81,
      false_next_question: 81,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 81,
      question_english: "Are your nails shiny white?",
      question_hindi: "क्या आपके नाखून चमकने लगे हैं?",
      true_next_question: 82,
      false_next_question: 82,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/hpb79.png",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 82,
      question_english: "Do you have yellow eyes?",
      question_hindi: "क्या आपकी आंखों में पीलापन है?",
      true_next_question: 83,
      false_next_question: 83,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/hpb80.png",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 83,
      question_english:
        "Do you feel any swelling in the left side of the neck?",
      question_hindi:
        "क्या आप के गले मे बांयी तरफ सूजन या गिल्टी महसूस होती है?",
      true_next_question: 84,
      false_next_question: 84,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/hpb81.png",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 84,
      question_english: "Do you feel any lump in your abdomen with your hand?",
      question_hindi: "क्या आपको अपने हाथ से पेट में कोई गांठ महसूस होती है ?",
      true_next_question: 85,
      false_next_question: 85,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 85,
      question_english:
        "Do you have abnormal pigmentation in the skin/darkening of skin colour?",
      question_hindi:
        "क्या आपकी त्वचा के रंग में कुछ बदलाव / या गहरा हो गया है?",
      true_next_question: 86,
      false_next_question: 86,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
    {
      question_no: 86,
      question_english: "Do you have any dilated veins seen over the abdomen?",
      question_hindi: "क्या आपके पेट पर फूली हुई नसे दिखती है?",
      true_next_question: 0,
      false_next_question: 0,
      question_answer: "ABSENT",
      question_desc: "",
      question_img: "https://dectrocel.com/explaination/hpb84.jpg",
      option: {
        option_1: "YES/हाँ",
        option_2: "NO/नहीं",
      },
      multiple_choice: [],
    },
  ],
};

export default questions;
